#!/bin/bash
###############################################################################
# Renders a native (non-Docker) Traefik configuration on macOS.
#
# Called by install_native_app.sh for the `traefik` native app. Produces:
#   <data_dir>/traefik.yml        static config (entrypoints, providers, api)
#   <data_dir>/dynamic/           dynamic config dir (file provider, watched)
#   <data_dir>/dynamic/apps.yml   one HTTP router+service per native app that
#                                 has a `port` in includes/nativeapps/vars/*
#
# It intentionally starts from a minimal working config rather than rendering
# the full Docker-oriented Jinja2 templates in
# includes/dockerapps/templates/traefik/*.j2 (docker provider, Ansible vars) —
# those describe the richer routing/middleware/ACME setup to port incrementally.
#
# Ports: defaults to :8000 / :8443 so it runs as a plain LaunchAgent (no root).
# To use :80 / :443, edit traefik.yml and load it as a LaunchDaemon instead.
###############################################################################
set -euo pipefail

DATA_DIR="${1:?usage: render_traefik_config.sh <data_dir>}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VARS_DIR="${SCRIPT_DIR}/vars"
DYN_DIR="${DATA_DIR}/dynamic"
LOG_DIR="${HOME}/Library/Logs/ssd-native/traefik"
mkdir -p "${DYN_DIR}" "${LOG_DIR}"

HTTP_PORT="${SSD_TRAEFIK_HTTP_PORT:-8000}"
HTTPS_PORT="${SSD_TRAEFIK_HTTPS_PORT:-8443}"
DASH_PORT="${SSD_TRAEFIK_DASH_PORT:-8080}"

# ---- static config -------------------------------------------------------
if [ ! -f "${DATA_DIR}/traefik.yml" ]; then
  cat > "${DATA_DIR}/traefik.yml" <<EOF
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true          # API + dashboard on the 'traefik' entrypoint (:${DASH_PORT}, localhost)

ping:
  entryPoint: traefik

log:
  level: INFO
  filePath: "${LOG_DIR}/traefik.log"

accessLog:
  filePath: "${LOG_DIR}/access.log"
  format: json
  bufferingSize: 100

entryPoints:
  web:
    address: "127.0.0.1:${HTTP_PORT}"
  websecure:
    address: "127.0.0.1:${HTTPS_PORT}"
  traefik:
    address: "127.0.0.1:${DASH_PORT}"

providers:
  file:
    directory: "${DYN_DIR}"
    watch: true

# --- Optional: Let's Encrypt via Cloudflare DNS-01 -----------------------
# Uncomment and set CF_DNS_API_TOKEN in the LaunchAgent env to enable.
# certificatesResolvers:
#   cloudflare:
#     acme:
#       email: "you@example.com"
#       storage: "${DATA_DIR}/acme.json"
#       dnsChallenge:
#         provider: cloudflare
#         resolvers: ["1.1.1.1:53"]
EOF
  echo " * static config -> ${DATA_DIR}/traefik.yml"
else
  echo " * static config déjà présent -> ${DATA_DIR}/traefik.yml (laissé tel quel)"
fi

# ---- dynamic config: one router per native app with a port --------------
{
  echo "# generated by render_traefik_config.sh — one router/service per"
  echo "# includes/nativeapps/vars/*.yml that declares a port. Re-run the"
  echo "# traefik native install to regenerate."
  echo "http:"
  echo "  routers:"
  for f in "${VARS_DIR}"/*.yml; do
    app="$(basename "${f}" .yml)"
    [ "${app}" = "traefik" ] && continue
    p="$(sed -n 's/^port:[[:space:]]*//p' "${f}" | head -1)"
    [ -z "${p}" ] && continue
    printf "    %s:\n" "${app}"
    printf "      rule: 'Host(\`%s.local\`)'\n" "${app}"
    printf "      entryPoints: ['web']\n"
    printf "      service: '%s'\n" "${app}"
  done
  echo "  services:"
  for f in "${VARS_DIR}"/*.yml; do
    app="$(basename "${f}" .yml)"
    [ "${app}" = "traefik" ] && continue
    p="$(sed -n 's/^port:[[:space:]]*//p' "${f}" | head -1)"
    [ -z "${p}" ] && continue
    echo "    ${app}:"
    echo "      loadBalancer:"
    echo "        servers:"
    echo "          - url: \"http://127.0.0.1:${p}\""
  done
} > "${DYN_DIR}/apps.yml"
echo " * dynamic config -> ${DYN_DIR}/apps.yml"
