#!/bin/bash
###############################################################################
# bundle_render hook for `webui` (see vars/webui.yml).
#
# Writes ONE Traefik dynamic-config file putting the three webui services behind
# a single host with path-prefix routing — the native equivalent of the per-
# container traefik labels in dockerapps/pretasks/webui.yml:
#
#   Host(`<WEBUI_HOST>`)                       -> ssd-frontend    :3000   (prio 10)
#   Host(`<WEBUI_HOST>`) && PathPrefix(/season) -> saison-frontend :8001   (prio 90)
#   Host(`<WEBUI_HOST>`) && PathPrefix(/api/v1) -> ssd-backend     :8091   (prio 100)
#
# Output: <traefik-data>/dynamic/webui.yml  (picked up by the file provider,
# which watches that dir). Traefik's own native install must have run first.
#
# Override the host with SSD_WEBUI_HOST (default: ssd.local).
###############################################################################
set -euo pipefail

WEBUI_DATA_DIR="${1:?usage: render_webui_traefik.sh <webui_data_dir>}"
GREEN="${GREEN:-\033[0;32m}"; YELLOW="${YELLOW:-\033[0;33m}"; NC="${NC:-\033[0m}"

# By default the webui is the catch-all site on the Traefik web entrypoint —
# routing is by path only, so it answers on any host/IP (localhost, a LAN IP,
# a tunnel hostname) without per-host config. Set SSD_WEBUI_HOST to a hostname
# to scope it to that host instead (adds `Host(...) &&` to every rule).
WEBUI_HOST="${SSD_WEBUI_HOST:-}"
FRONTEND_PORT="${SSD_WEBUI_FRONTEND_PORT:-3001}"
SAISON_PORT="${SSD_WEBUI_SAISON_PORT:-8001}"
BACKEND_PORT="${SSD_WEBUI_BACKEND_PORT:-8091}"

if [ -n "${WEBUI_HOST}" ]; then
  HOST_CLAUSE="Host(\`${WEBUI_HOST}\`) && "
  FRONT_RULE="Host(\`${WEBUI_HOST}\`)"
  SCOPE="host ${WEBUI_HOST}"
else
  HOST_CLAUSE=""
  FRONT_RULE="PathPrefix(\`/\`)"
  SCOPE="tout hôte (routage par préfixe)"
fi

# <storage>/native/webui -> <storage>/native/traefik/dynamic
TRAEFIK_DYN_DIR="$(cd "${WEBUI_DATA_DIR}/.." && pwd)/traefik/dynamic"
if [ ! -d "${TRAEFIK_DYN_DIR}" ]; then
  echo -e "${YELLOW} * ${TRAEFIK_DYN_DIR} absent — installez d'abord le Traefik natif (install_native_app.sh traefik)${NC}" >&2
  mkdir -p "${TRAEFIK_DYN_DIR}"
fi

OUT="${TRAEFIK_DYN_DIR}/webui.yml"
cat > "${OUT}" <<EOF
# generated by render_webui_traefik.sh — the ssdv2 WebUI bundle (${SCOPE}).
# Re-run: includes/nativeapps/install_native_app.sh webui
http:
  routers:
    webui-backend:
      rule: "${HOST_CLAUSE}PathPrefix(\`/api/v1\`)"
      entryPoints: ["web"]
      service: webui-backend
      priority: 100
    webui-saison:
      rule: "${HOST_CLAUSE}PathPrefix(\`/season\`)"
      entryPoints: ["web"]
      service: webui-saison
      priority: 90
    webui-frontend:
      rule: "${FRONT_RULE}"
      entryPoints: ["web"]
      service: webui-frontend
      priority: 10

  services:
    webui-backend:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:${BACKEND_PORT}"
    webui-saison:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:${SAISON_PORT}"
    webui-frontend:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:${FRONTEND_PORT}"
EOF

echo -e " ${GREEN}* config Traefik webui -> ${OUT}  (host: ${WEBUI_HOST})${NC}"
